# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('barcode', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='バーコード')),
                ('name', models.CharField(max_length=256, verbose_name='品名')),
                ('manage_no', models.CharField(max_length=128, verbose_name='資産管理番号')),
                ('manage_user', models.CharField(max_length=256, verbose_name='管理者')),
                ('comment', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing', models.CharField(max_length=64, verbose_name='処理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nfc_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='NFCID')),
                ('employee_no', models.CharField(max_length=64, verbose_name='社員番号')),
                ('name', models.CharField(max_length=256, verbose_name='氏名')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.User'),
        ),
    ]
