# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('barcode', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name=b'\xe3\x83\x90\xe3\x83\xbc\xe3\x82\xb3\xe3\x83\xbc\xe3\x83\x89')),
                ('name', models.CharField(max_length=255, verbose_name=b'\xe5\x93\x81\xe5\x90\x8d')),
                ('manage_no', models.CharField(max_length=255, verbose_name=b'\xe8\xb3\x87\xe7\x94\xa3\xe7\xae\xa1\xe7\x90\x86\xe7\x95\xaa\xe5\x8f\xb7')),
                ('manage_user', models.CharField(max_length=255, verbose_name=b'\xe7\xae\xa1\xe7\x90\x86\xe8\x80\x85')),
                ('comment', models.TextField(blank=True, verbose_name=b'\xe5\x82\x99\xe8\x80\x83')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing', models.CharField(max_length=64, verbose_name=b'\xe5\x87\xa6\xe7\x90\x86')),
                ('update_at', models.DateTimeField(verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x99\x82\xe9\x96\x93')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.Equipment', verbose_name=b'\xe5\x82\x99\xe5\x93\x81')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('employee_no', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name=b'\xe7\xa4\xbe\xe5\x93\xa1\xe7\x95\xaa\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=255, verbose_name=b'\xe6\xb0\x8f\xe5\x90\x8d')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.User', verbose_name=b'\xe3\x83\xa6\xe3\x83\xbc\xe3\x82\xb6\xe3\x83\xbc'),
        ),
    ]
